name: a2kit CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash
    
jobs:
  test:
    strategy:
      matrix:
        node-version: [20.x]
        OS: [macos-latest]

    runs-on: ${{ matrix.OS }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download a2kit
      uses: robinraju/release-downloader@v1
      with:
        repository: 'dfgordon/a2kit'
        latest: true
        fileName: 'a2kit-aarch64-*'
        extract: true
    - name: syntax check BASIC
      run: |
        cat ./src/basic/startup.bas | ./a2kit verify -t atxt
        cat ./src/basic/map.bas | ./a2kit verify -t atxt
        cat ./src/basic/paint.bas | ./a2kit verify -t atxt
        cat ./src/basic/repaint.bas | ./a2kit verify -t atxt
        cat ./src/basic/tile.bas | ./a2kit verify -t atxt
    - name: syntax check Merlin
      run: |
        cat ./src/merlin/bitstream.S | ./a2kit verify -t mtxt -w ~+/src/merlin --config "{\"version\":\"Merlin 32\"}"
        cat ./src/merlin/core.S | ./a2kit verify -t mtxt -w ~+/src/merlin --config "{\"version\":\"Merlin 32\"}"
        cat ./src/merlin/decode.S | ./a2kit verify -t mtxt -w ~+/src/merlin --config "{\"version\":\"Merlin 32\"}"
        cat ./src/merlin/dhrlib.S | ./a2kit verify -t mtxt -w ~+/src/merlin --config "{\"version\":\"Merlin 32\"}"
        cat ./src/merlin/draw.S | ./a2kit verify -t mtxt -w ~+/src/merlin --config "{\"version\":\"Merlin 32\"}"
        cat ./src/merlin/encode.S | ./a2kit verify -t mtxt -w ~+/src/merlin --config "{\"version\":\"Merlin 32\"}"
        cat ./src/merlin/map.S | ./a2kit verify -t mtxt -w ~+/src/merlin --config "{\"version\":\"Merlin 32\"}"
        cat ./src/merlin/parse.S | ./a2kit verify -t mtxt -w ~+/src/merlin --config "{\"version\":\"Merlin 32\"}"
